title: Keino Blog
baseurl: "" # For github pages
description: >- # You can edit footer in _includes/footer.md 
  莫问收获 但问耕耘

google_analytics: # Enter your tracking ID. Not available on IPFS

twitter_cards: off # Not available on IPFS. /assets/logo.png required
twitter_username: 

# Build settings
markdown: kramdown
sass:
  style: compressed
